name: Dev Tools Version Action
description: Version Stuff

inputs:
  versionFile:
    description: Path to a json file that contains the target verion
    required: false
  version:
    description: The target version
    required: false

  branch:
    description: "Override the branch. {v | release}/{latest | {major}[.{minor}] } {major}[.{minor}]. examples: v/1  v/1.1  release/1.1 v/latest"
    required: false

  existingVersions:
    description: Override the released versions. One per line
    required: false

outputs:
  branch:
    description: The source branch
  branchLatest:
    description: The latest version for this branch
  isSource:
    description: The branch is a release source branch
  isTarget:
    description: The branch is a release target branch
  targetVersion:
    description: The version specified in the version file
  sourceVersion:
    description: The the highest version of the branch
  versionUnchanged:
    description: If version specified matches the highest branch version


  versionMajor:
    description: The major component of the version
  versionMinor:
    description: The minor component of the version
  versionPatch:
    description: The patch component of the version
  versionBuild:
    description: The build components of the version
  versionPrerelease:
    description: The prerelease component of the version
  versionPrereleaseBuild:
    description: The prerelease build component of the version
  versionIsPrerelease:
    description: The version has a prerelease component
  versionIsStable:
    description: The version does not have a prerelease component and is version 1.0 or greater
  versionValidReleaseMinimum:
    description: The version passes minimum ver validation for release
  versionValidReleaseMaximum:
    description: The version passes maximum ver validation for release

runs: 
  using: 'node16'
  main: 'dist/index.js'
