name: Publish Release 

on:
  push:
    branches:
      - "release/*"

jobs:
  publish:
    name: Publish a new version
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Check Version
        id: version
        uses: cpdevtools/action-versions@latest
        with:
          failInvalidCanCreate: true

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
        with:
          tag_name: v${{ steps.version.outputs.targetVersion }}
          release_name: Release v${{ steps.version.outputs.targetVersion }}
          body: |
            Generated Release v${{ steps.version.outputs.targetVersion }}
          draft: false
          prerelease: ${{ steps.version.outputs.targetIsPrerelease }}

      - name: Apply latest/prerelease tag

        #uses: actions/github-script@v3
        uses: ./
        with: 
          failInvalidCanCreate: true     
          createTags: all
