name: Publish Release 

on:
  push:
    branches:
      - "release/*"

jobs:
  publish:
    name: Publish a new version
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: pnpm/action-setup@v2.2.2
        with:
          version: 7.6.0
          run_install: false

      - uses: actions/setup-node@v3
        with:
          node-version: 16.17.x
          cache: 'pnpm'
          cache-dependency-path: pnpm-lock.yaml

      - name: Install Dependencies
        run: pnpm install --frozen-lockfile --ignore-scripts


      - name: Check Version
        id: version
        uses: ./
        with:
          failIfNotValidNew: true


      - name: Create tag
  #      id: tag_version
        uses: mathieudutour/github-tag-action@v5.5
        with:
#          github_token: ${{ github.token }}
          custom_tag: v${{ steps.version.outputs.targetVersion }}
      
      - name: Create release
 #       id: create_release
        uses: softprops/action-gh-release@v1
 #       env:
    #      GITHUB_TOKEN: ${{ github.token }}
        with:
          tag_name: v${{ steps.version.outputs.targetVersion }}
          name: Version ${{ steps.version.outputs.targetVersion }}
          body: |
            Generated Release ${{ steps.version.outputs.targetVersion }}
          draft: false
          prerelease: ${{ steps.pkgVersion.outputs.targetIsPrerelease }}