name: Test 


on:
  push:
    branches:
      - "*"
      - "release/*"
      - "v/*"


jobs:
  build:
    name: Build and run the action
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: pnpm/action-setup@v2.2.2
        with:
          version: 7.6.0
          run_install: false

      - uses: actions/setup-node@v3
        with:
          node-version: 16.17.x
          cache: 'pnpm'
          cache-dependency-path: pnpm-lock.yaml

      - name: Install Dependencies
        run: pnpm install --frozen-lockfile --ignore-scripts 

      - name: Build 
        run: pnpm run build
      
      - name: Run 
        uses: ./
        with:
          existingVersions: |
            v0.0.1-dev.0
            v1.0.0
            some-other-tag
            v1.1.0
            v1.1.1
            v1.1.2
            v1.2.0-dev.0



